#startup
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8888
#Spring
spring:
    application:
        name: mama-bike
#profile
    profiles:
        active: prod
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
#datasource
    datasource:
        # druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#mybatis
mybatis:
    mapper-locations: classpath:com/coder520/**/**.xml
    type-aliases-package: classpath:com.coder520.**.entity

#log
logging:
    config: classpath:logback.xml

#activeMQ  redis  mogo placed in dev or prod



